# Terraform pipeline

trigger:
  - master

variables:
  tf_version: "latest" # what version of terraform should be used
  tf_state_rg: "blogpost-tfstate-rg" # name of the resource group to create/use for the terraform state file
  tz_state_location: "uksouth" # location of the resource group to create/use for the terraform state file
  tf_state_sa_name: "blogposttfstatesa" # name of of the storage account to create/use for the terraform state file
  tf_state_container_name: "tfstate" # name of of the container to create/use for the terraform state file
  tf_state_tags: ("env=blogpost-terraform-devops-pipeline" "deployedBy=devops") # tags for the resources above which support tagging
  tf_environment: "dev" # enviroment name, used for the statefile name

pool:
  vmImage: "ubuntu-latest"

stages:
  # Run Terrascan, upload results and halt if there any problems found
  ######################################################################

  - stage: "runTerrascan"
    displayName: "Run Terrascan"
    jobs:
      - job: "runTerrascan"
        displayName: "Download, run and publish results of Terrascan scan"
        steps:
          - bash: |
              docker pull accurics/terrascan
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Pull > Terrascan"

          - bash: |
              echo $(docker run --rm -t -v $(pwd):/iac -w /iac accurics/terrascan scan -t azure -o junit-xml) > Terrascan-Report.xml
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Run > Terrascan"

          - task: PublishTestResults@2
            displayName: "Publish > Terrascan scan results"
            inputs:
              testRunTitle: "Terrascan Results"
              failTaskOnFailedTests: true
              testResultsFormat: "JUnit"
              testResultsFiles: "Terrascan-Report.xml"
              searchFolder: "$(System.DefaultWorkingDirectory)"

  # Check the Statefile Azure Storage Account exists
  ######################################################################

  - stage: "CheckStatefile"
    displayName: "Configure Terraform Statefile Storage Account"
    dependsOn:
      - "runTerrascan"
    jobs:
      - job: "runTerrascan"
        displayName: "Create/Check the Terraform Statefile Azure Storage Account"
        steps:
          - task: AzureCLI@2
            displayName: "Create/Check > Terraform Statefile Azure Storage Account"
            inputs:
              azureSubscription: "$(SUBSCRIPTION_NAME)"
              addSpnToEnvironment: true
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                TAGS=$(tf_state_tags)
                az group create --name $(tf_state_rg) --location $(tz_state_location) --tags "${TAGS[@]}"
                az storage account create --resource-group $(tf_state_rg) --name $(tf_state_sa_name) --sku Standard_GRS --encryption-services blob --tags "${TAGS[@]}"
                ACCOUNT_KEY=$(az storage account keys list --resource-group $(tf_state_rg) --account-name $(tf_state_sa_name) --query [0].value -o tsv)
                az storage container create --name $(tf_state_container_name) --account-name $(tf_state_sa_name) --account-key $ACCOUNT_KEY
                echo "##vso[task.setvariable variable=tf_state_sa_key]$ACCOUNT_KEY"

  # Run Terraform - uses https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform
  ######################################################################

  - stage: "runTerraform"
    displayName: "Download and run Terraform"
    dependsOn:
      - "runTerrascan"
      - "CheckStatefile"
    jobs:
      - job: "TerraformInstall"
        displayName: "Terraform > Install"
        steps:
          - task: TerraformInstaller@0
            displayName: "Install > terraform"
            inputs:
              terraformVersion: "$(tf_version)"

      - job: "TerraformInit"
        displayName: "Terraform > Init"
        dependsOn:
          - "TerraformInstall"
        steps:
          - task: TerraformCLI@0
            displayName: "Run > terraform init"
            inputs:
              command: "init"
              backendServiceArm: "$(SUBSCRIPTION_NAME)"
              backendType: "azurerm"
              backendAzureRmResourceGroupName: "$(tf_state_rg)"
              backendAzureRmStorageAccountName: "$(tf_state_sa_name)"
              backendAzureRmContainerName: $(tf_state_container_name)
              backendAzureRmKey: "$(tf_environment).terraform.tstate"

      - job: "TerraformPlan"
        displayName: "Terraform > Plan"
        dependsOn:
          - "TerraformInstall"
          - "TerraformInit"
        steps:
          - task: TerraformCLI@0
            displayName: "Run > terraform plan"
            inputs:
              command: "plan"
              environmentServiceName: "$(SUBSCRIPTION_NAME)"
              publishPlanResults: "PlanResults"
              commandOptions: "-out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode"

      - job: "TerraformApply"
        displayName: "Terraform > Apply"
        dependsOn:
          - "TerraformInstall"
          - "TerraformInit"
          - "TerraformPlan"
        steps:
          - task: TerraformCLI@0
            displayName: "Run > terraform apply"
            condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
            inputs:
              command: "apply"
              environmentServiceName: "$(SUBSCRIPTION_NAME)"
              commandOptions: "$(System.DefaultWorkingDirectory)/terraform.tfplan"
