# Terraform pipeline

trigger:
  - master

variables:
  tf_version: "latest" # what version of terraform should be used
  tf_state_rg: "rg-blogpost-tfstate" # name of the resource group to create/use for the terraform state file
  tz_state_location: "uksouth" # location of the resource group to create/use for the terraform state file
  tf_state_sku: "Standard_RAGRS" # sku to use when creating the storeage account to create/use for the terraform state file
  tf_state_sa_name: "blogposttfstatesa" # name of of the storage account to create/use for the terraform state file
  tf_state_container_name: "tfstate" # name of of the container to create/use for the terraform state file
  tf_environment: "dev" # enviroment name, used for the statefile name

pool:
  vmImage: "ubuntu-latest"

stages:
  # Run Terrascan, upload results and halt if there any problems found
  ######################################################################

  - stage: "runTerrascan"
    displayName: "Terraform - Run Terrascan"
    jobs:
      - job: "runTerrascan"
        displayName: "Download, run and publish results of Terrascan scan"
        steps:
          - bash: |
              docker pull accurics/terrascan
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Pull > Terrascan"

          - bash: |
              echo $(docker run --rm -t -v $(pwd):/iac -w /iac accurics/terrascan scan -t azure -o junit-xml) > Terrascan-Report.xml
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Run > Terrascan"

          - task: PublishTestResults@2
            inputs:
              testRunTitle: "Terrascan Results"
              failTaskOnFailedTests: true
              testResultsFormat: "JUnit"
              testResultsFiles: "Terrascan-Report.xml"
              searchFolder: "$(System.DefaultWorkingDirectory)"
            displayName: "Publish > Terrascan scan results"

  # Run Terraform - uses https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform
  ######################################################################

  - stage: "runTerraform"
    displayName: "Terraform - Tasks"
    dependsOn:
      - "runTerrascan"
    jobs:
      - job: "TerraformJobs"
        displayName: "Terraform > install, init, plan & apply"
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: "$(tf_version)"
            displayName: "Install > terraform"

          - task: TerraformCLI@0
            inputs:
              command: "init"
              backendType: "azurerm"
              backendServiceArm: "$(SUBSCRIPTION_NAME)"
              ensureBackend: true
              backendAzureRmResourceGroupName: "$(tf_state_rg)"
              backendAzureRmResourceGroupLocation: "$(tz_state_location)"
              backendAzureRmStorageAccountName: "$(tf_state_sa_name)"
              backendAzureRmStorageAccountSku: "Standard_RAGRS"
              backendAzureRmContainerName: $(tf_state_container_name)
              backendAzureRmKey: "$(tf_environment).terraform.tstate"
            displayName: "Run > terraform init"

          - task: TerraformCLI@0
            inputs:
              command: "plan"
              environmentServiceName: "$(SUBSCRIPTION_NAME)"
              publishPlanResults: "PlanResults"
              commandOptions: "-out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode"
            displayName: "Run > terraform plan"

          - task: TerraformCLI@0
            condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
            inputs:
              command: "apply"
              environmentServiceName: "$(SUBSCRIPTION_NAME)"
              commandOptions: "$(System.DefaultWorkingDirectory)/terraform.tfplan"
            displayName: "Run > terraform apply"
